#!/bin/bash

#  docker-sync-time.sh
#  docker-sync-time
#
#  Created by ArunvelSriram on 26/12/16.
#  Copyright © 2016 ArunvelSriram. All rights reserved.

# Wait for reconnection for 300 seconds
for i in {1..300}; do
  nc 8.8.8.8 53 -z 2> /dev/null
  if [ $? -eq 0 ]; then
    # Call docker to sync time
    /usr/local/bin/docker run --rm --privileged --pid=host \
      walkerlee/nsenter -t 1 -m -u -i -n ntpd -d -q -n -p \
      `if [[ -f /etc/ntp.conf ]]; then cat /etc/ntp.conf | \
      awk '{ print $2 }'; else echo 'pool.ntp.org'; fi`
    break
  else
    sleep 1
  fi
done
